language: python
python:
  - "3.6"

env:
  global:
    - PGPORT=5432

services:
  - postgresql

before_install:
  - sudo apt update
  - pip install poetry
  - poetry --version

install:
  - cd backend
  - poetry install -vvv

before_script:
  - psql --version
  - psql -c 'CREATE DATABASE broccoli;' -U postgres
  - psql -c 'CREATE DATABASE test_broccoli;' -U postgres

script:
  - poetry run task format
  - poetry run task lint
  - poetry run pytest -V
  - poetry run task test --cov=broccoli tests/

after_success:
  - coveralls
