language: python
python:
  - 3.6

env:
  global:
    - PGPORT=5432

services:
  - postgresql

before_install:
  - sudo apt update
  - pip install poetry
  - poetry --version

install:
  - cd backend
  - poetry install -vvv

before_script:
  - psql --version
  - psql -c 'CREATE DATABASE broccoli;' -U postgres

script:
  - pwd
  - poetry run black .
  - poetry run pytest -V
  - poetry run pytest --cov=broccoli tests/

after_success:
  - coveralls
