"""created Entry table and related associations

Revision ID: 04d4615b5139
Revises: 13b49f1e7bbf
Create Date: 2021-06-09 14:52:40.920570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "04d4615b5139"
down_revision = "13b49f1e7bbf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("items", "description", existing_type=sa.VARCHAR(), nullable=True)
    op.add_column("users", sa.Column("entry_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "users", "entries", ["entry_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_column("users", "entry_id")
    op.alter_column("items", "description", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
