"""recreating entries table

Revision ID: 3b3c7e99d5d3
Revises: 04d4615b5139
Create Date: 2021-06-09 15:01:25.945079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3b3c7e99d5d3"
down_revision = "04d4615b5139"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("entries", "item_id")
    op.drop_column("entries", "user_id")
    op.alter_column("items", "description", existing_type=sa.VARCHAR(), nullable=True)
    op.add_column("users", sa.Column("entry_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "users", "entries", ["entry_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_column("users", "entry_id")
    op.alter_column("items", "description", existing_type=sa.VARCHAR(), nullable=False)
    op.add_column(
        "entries",
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "entries",
        sa.Column("item_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
