"""added goal attribute to user model

Revision ID: 708171308c9c
Revises: a37a05d793cc
Create Date: 2021-06-15 19:02:25.204180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "708171308c9c"
down_revision = "a37a05d793cc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("goal", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "goal")
    # ### end Alembic commands ###
