"""added personal details for users

Revision ID: a37a05d793cc
Revises: d6a6a542ab84
Create Date: 2021-06-15 18:29:49.089687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a37a05d793cc"
down_revision = "d6a6a542ab84"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("height", sa.Float(), nullable=True))
    op.add_column("users", sa.Column("weight", sa.Float(), nullable=True))
    op.add_column("users", sa.Column("age", sa.Integer(), nullable=True))
    op.add_column("users", sa.Column("sex", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "sex")
    op.drop_column("users", "age")
    op.drop_column("users", "weight")
    op.drop_column("users", "height")
    # ### end Alembic commands ###
