"""goal attribute string

Revision ID: c2bf2dba90ac
Revises: 708171308c9c
Create Date: 2021-06-15 19:18:30.899813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c2bf2dba90ac"
down_revision = "708171308c9c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("goal", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "goal")
    # ### end Alembic commands ###
