"""added calories column to items

Revision ID: e28ca79033e2
Revises: c4329d1e6f48
Create Date: 2021-05-25 17:27:54.975665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e28ca79033e2"
down_revision = "c4329d1e6f48"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("items", sa.Column("calories", sa.Integer(), nullable=False))
    op.alter_column("items", "title", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("items", "description", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("items", "description", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("items", "title", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("items", "calories")
    # ### end Alembic commands ###
